openapi: 3.0.0
info:
  title: City Service
  description:
    A simple service that allows CRUD operations for a city tracker.
  version: 0.0.1
servers:
  - url: 'http://localhost:8080'
    description: Local dev server
paths:
  /city:
    post:
      summary: Creates a new city object with given information.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/City'
      responses:
        '201':
          description: A city object
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/City'
        '400':
          description: Invalid request syntax.
          
    get:
      summary: Retrieve all cities.
      responses:
        '200':
          description: All cities list(cityList)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/City'
          
  /city/{name}:
    get:
      summary: Retrieves the entry for the City with the given name.
      parameters: 
        - name: name
          in: path
          required: true
          description: grab the city object matching city name.
          schema:
            type: string
      responses:
        '200':
          description: City object matching matching name.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/City'
      
    delete:
      summary: Deletes the entry for the city object with matching city name.
      parameters: 
        - name: name
          in: path
          required: true
          description: delete the city object with matching city name.
          schema:
            type: string
      responses:
        '200':
          description: City successfully deleted.
          
    put:
      summary: Updated the entry for the city with the matching city name.
      parameters: 
        - name: name
          in: path
          required: true
          description: name of the city you would like to update.
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/City'
      responses:
        '200':
          description: City successfully updated.
        '422':
          description: City name on path must match the name in the City object.
components:
  schemas:
    City:
      properties:
        name:
          type: string
        state:
          type: string
        population:
          type: number
        isCapital:
          type: boolean
      required: 
        - name
        - state
        - population
        - isCapital
